### ISSUE TITLE
How to make solvers run until lower precision?

### ISSUE THREAD

**Issue by QB3** [benchopt/benchopt#266]
I would like to use benchopt to compare some solvers (here blitz vs celer). Sometimes solvers do not run until machine precision convergence (blitz here). To make them run until lower duality gap I increased timeout and max-runs, but in this case celer is running for too long (because max-runs is the number of subproblems to solve).
Is there a way to have have more precision for blitz, without exploding in time for celer?
![Capture d’écran de 2021-12-13 10-18-14](https://user-images.githubusercontent.com/20907043/145839469-f6a9f6ab-53f8-4982-af0f-240ea75209bb.png)

Should I tune the max-run growing policy?

**Comment by tomMoral** [comment]
You should tune the way blitz is stopped in the solver here: https://github.com/benchopt/benchmark_lasso/blob/main/solvers/blitz.py#L33

If blitz needs more iterations, you can simply multiply `n_iter` by a fixed constant or poser in the `run` method.
`https://github.com/benchopt/benchmark_lasso/blob/main/solvers/blitz.py#L33

**Comment by mathurinm** [comment]
I think it's because solvers like celer and blitz aren't tailored to a geometric growth of their `n_iter`. To me it makes little sense to run celer with 100 subproblems definitions, but if you run in debug mode you'll see that we ask max_iter=167  

The graph seems to show a weird situation where the first decrease is quite fast for both solvers, and then celer suddenly slows down, to me it's more that it's stuck on some subproblems because we ask for a tolerance too low or something.

**Comment by tomMoral** [comment]
For now, we take geometric growth because it is what works best for many different solvers if we don't want to get stuck.
But I agree that this is not always adapted. There is 2 mechanisms to improve this:

- We can adapt what the `n_iter` means in the definition of `run`, for instance taking `n_iter = np.log(n_iter)` if you think it makes more sense for `celer` or `blitz`.
- We can define a `get_next` method per solver that get the previous `stop_val` and return the next one. (Just rediscover this one yesterday.. we still lack a lot of doc!)

**Comment by mathurinm** [comment]
@QB3 do you know what makes blitz stop here (because of benchopt, of itself) ? Because there is also a timing mechanism inside its solver:
https://github.com/tbjohns/BlitzL1/blob/master/src/solver.cpp#L540 
though the value seems very, very high by default:
https://github.com/tbjohns/BlitzL1/blob/master/src/solver.h#L59

**Comment by mathurinm** [comment]
@QB3 can you reproduce in terms of objective value ? Blitz also has a poor duality gap estimate.
Now that we used a linear increase in n_iter, and if you no longer use the tolerance strategy of blitz, does it still happen ?

**Comment by QB3** [comment]
> Now that we used a linear increase in n_iter, and if you no longer use the tolerance strategy of blitz, does it still happen ?

It was fixed with the linear n_iter growing, thx!
