### ISSUE TITLE
CLI - ``benchopt`` prints "already available" even for uninstalled solvers

### ISSUE THREAD

**Issue by Badr-MOUFAD** [benchopt/benchopt#553]
# Description
When attempting to install a solver through CLI, ``benchopt`` may prints "already available" and thereby not install the solver despite the latter not being installed.

# Reproduce

Assuming that ``benchopt`` is already installed

```bash
git clone https://github.com/mathurinm/benchmark_lasso.git@approx
cd benchmark_lasso

benchopt install . -s apgcd
```

or from the ``benchmark_lasso`` repo

```bash
git remote add mathurinm https://github.com/mathurinm/benchmark_lasso.git
git fetch mathurinm approx
git checkout approx

benchopt install . -s apgcd
```

# Debugging

Investigation (thanks to @mathurinm) shows that this happens because the import of the [solver is done inside the ``run`` function](https://github.com/benchopt/benchmark_lasso/pull/63/files#diff-2b2acee23dfb466767ea8234aef14182963cbde28c8400b341d2c76e3e9f7e6fR30) instead of the safe import context. Therefore it is not a bug in ``benchopt``.

# Suggestion

It would much better to elucidate this to the user, for instance by printing a message to hint at putting all imports in safe import context.

**Comment by mathurinm** [comment]
To summarize: the check install does not check the requirements from the `requirements` attribute of a Solver, it checks that everything in the `safe_import_ctx` is there. Therefore one can end up with the message "solver already installed" whereas it's not the case, just because the solver is not structured properly.

Maybe it can be solved by a more explicit message, along the lines of "all requirements in safe_import_ctx installed or no safe_import_ctx" ?

**Comment by mathurinm** [comment]
I don't think the current process is broken, so no need to force reinstallation IMO (we don't know what it may change, solving environments may have an overhead too).

I am more in favor of editing the CLI feedback to make it clearer ("all imports in safe_import_ctx available"? maybe a link to some example of safe_import_ctx in the doc)
