### ISSUE TITLE
BUG run_once strategy

### ISSUE THREAD

**Issue by antoinecollas** [benchopt/benchopt#708]
When using the `run_once` strategy, solvers are still run 4 times instead of 1.
To avoid this, `max-runs` must be set `0`.
I am not sure it is the intended behavior or not...

**Comment by tomMoral** [comment]
can you post the code of a solver that shows this issue?

**Comment by antoinecollas** [comment]
I did a mistake, I close the issue!

**Comment by tomMoral** [comment]
For the record, the error was that `"run_once"` was set for `strategy` instead of `sampling_strategy`.

I think we should update `benchopt test` to check the class attributes of each solver and raise an error when this attribute does not match any benchopt based attributes (with a way to declare the one that are specific to the benchmark).
