### ISSUE TITLE
ENH gain time for some solvers by returning list of times and iterates

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#88]
When we code a solver specifically for a benchmark, we can return a list of `(time, iterate)` (or two lists), so that we get one full convergence curve per run, instead of having to run with different max_iter or tol. I think the time to get a curve should go from quadratic in max_iter to linear.

This means we trust the user to dump the correct time, but the curves could be altered anyways with the current process, so IMO we should assume good faith.

**Comment by agramfort** [comment]
this was a design decision from the start to support all systems and
programming languages no matter
how they use time estimates.

>

**Comment by mathurinm** [comment]
The time is a major bottleneck for me. If you take the example from the doc:
![image](https://user-images.githubusercontent.com/8993218/101355432-d71a3180-3896-11eb-872b-03778caa1afc.png)
It could be run in less than 5 * 2s, but it takes close to a minute on my machine.

I agree *we should keep the default behavior* which is very robust, but that doesn't mean we shouldn't allow for more efficient ones when possible

**Comment by agramfort** [comment]
it's a trade off. It depends if you consider computation time free. I would
just use dragos in the background and move on

>

**Comment by tomMoral** [comment]
Small note @mathurinm the complexity is not qudratic but O(T logT) :wink: 

I agree that adding this option might help diffuse `benchopt`.
When you develop a new solver and you want to use `benchopt` to evaluate it (which we would like to promote), you might want to reduce the time to be able to iterate more quickly so having such option would help a lot.

To me, it seems like a low complexity enhancement as it should be quite easy to support both.
The main issue here is that we need to agree on a good API.

**Comment by mathurinm** [comment]
I believe that assuming an access to drago-like is restrictive for the potential user base. Being able to iterate quickly would be nice IMO

**Comment by mathurinm** [comment]
solved by implementing the callback stopping strategy in #137

**Comment by jolars** [comment]
Any chance of reconsidering this? I understand that the callback strategy can be used to solve this but that this would require that the solvers are coded within the benchopt framework. I'm sure that's okay in many cases, but at least on the project I'm working on right now we're coding our algorithm as a separate module (which I think makes most sense) and not directly in benchopt.

Setting aside the issue of overhead from the current approach, it may also be useful to just have the more fine-grained information from the full progress of the solver. Some solvers do not converge monotonically or have otherwise interesting behavior which doesn't necessarily show with the current approach (thinking of accelerated gradient descent methods or stochastic methods for instance). 

I would be happy to work on a PR to support this.

**Comment by agramfort** [comment]
can you be more specific @jolars on what you suggest in terms of code/API/changes?

**Comment by jolars** [comment]
Add another `stopping_strategy` called "manual" or "external" or something similar. For a solver with that strategy, expect a return object that contains estimates from the solver and the time points at which they were collected for each of those estimates.

By the way, this would also solve https://github.com/benchopt/benchopt/issues/260.

**Comment by agramfort** [comment]
let's see what @tomMoral or @mathurinm think

I could be convinced
